
services:

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=code-converse-db
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - "3306:3306"
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  backend-server:
    image: 'code-converse:latest'
    build:
      context: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/code-converse-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  frontend-server:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/my-app
      - /my-app/node_modules
    ports:
      - "4200:4200"
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
